//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('messages')
export class messagesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  Sender: number;

  @Column('integer', { nullable: true })
  Receiver: number;

  @Column('text', { nullable: true })
  MessageContent: string;

  @Column('date', { nullable: true })
  Timestamp: Date;
}
