//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('profiles')
export class profilesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  ProfilePicture: string;

  @Column('text', { nullable: true })
  Biography: string;

  @Column('text', { nullable: true })
  RelationshipStatus: string;

  @Column('text', { nullable: true })
  Interests: string;
}
