//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('users')
export class usersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  Name: string;

  @Column('integer', { nullable: true })
  Age: number;

  @Column('text', { nullable: true })
  Gender: string;

  @Column('text', { nullable: true })
  Location: string;

  @Column('text', { nullable: true })
  Picture: string;

  @Column('text', { nullable: true })
  Interests: string;

  @Column('text', { nullable: true })
  Family: string;

  @Column('real', { nullable: true })
  Height: number;

  @Column('real', { nullable: true })
  Weight: number;

  @Column('text', { nullable: true })
  Education: string;

  @Column('text', { nullable: true })
  Job: string;

  @Column('text', { nullable: true })
  Cast: string;
}
