//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    users: {
      name: 'Users',
      fields: {
        Name: 'Name',
        Age: 'Age',
        Gender: 'Gender',
        Location: 'Location',
        Picture: 'Picture',
        Interests: 'Interests',
        Family: 'Family',
        Height: 'Height',
        Weight: 'Weight',
        Education: 'Education',
        Job: 'Job',
        Cast: 'Cast',
        id: 'id',
      },
    },
    messages: {
      name: 'Messages',
      fields: {
        Sender: 'Sender',
        Receiver: 'Receiver',
        MessageContent: 'Message Content',
        Timestamp: 'Timestamp',
        id: 'id',
      },
    },
    profiles: {
      name: 'Profiles',
      fields: {
        ProfilePicture: 'Profile Picture',
        Biography: 'Biography',
        RelationshipStatus: 'Relationship Status',
        Interests: 'Interests',
        id: 'id',
      },
    },
    matches: {
      name: 'Matches',
      fields: {
        UserId1: 'User Id1',
        UserId2: 'User Id2',
        MatchStatus: 'Match Status',
        Timestamp: 'Timestamp',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    users: {
      name: 'Users (fr)',
      fields: {
        Name: 'Name (fr)',
        Age: 'Age (fr)',
        Gender: 'Gender (fr)',
        Location: 'Location (fr)',
        Picture: 'Picture (fr)',
        Interests: 'Interests (fr)',
        Family: 'Family (fr)',
        Height: 'Height (fr)',
        Weight: 'Weight (fr)',
        Education: 'Education (fr)',
        Job: 'Job (fr)',
        Cast: 'Cast (fr)',
        id: 'id',
      },
    },
    messages: {
      name: 'Messages (fr)',
      fields: {
        Sender: 'Sender (fr)',
        Receiver: 'Receiver (fr)',
        MessageContent: 'Message Content (fr)',
        Timestamp: 'Timestamp (fr)',
        id: 'id',
      },
    },
    profiles: {
      name: 'Profiles (fr)',
      fields: {
        ProfilePicture: 'Profile Picture (fr)',
        Biography: 'Biography (fr)',
        RelationshipStatus: 'Relationship Status (fr)',
        Interests: 'Interests (fr)',
        id: 'id',
      },
    },
    matches: {
      name: 'Matches (fr)',
      fields: {
        UserId1: 'User Id1 (fr)',
        UserId2: 'User Id2 (fr)',
        MatchStatus: 'Match Status (fr)',
        Timestamp: 'Timestamp (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
